### ISSUE TITLE
report 4 - Weekly Summary Report - No. of requests closed by organization 

### ISSUE THREAD

**Issue by MrClemRkz** [LSFLK/request-management#42]

**Comment by nshamit** [comment]
Title: Weekly Summary Report - No. of requests closed by organization

Bold Total
Include “No. of issues open” underneath total

Under organization, they could list the division so reports can maintain the same format and change the headings/ field titles. Instead of Category and Subcategory, you can use Organization and Division

**Comment by YujithIsura** [comment]
this issue referring #40
